version: "3"
services:
  nginx: 
    build: 
      context: ./webserver

  nginx2:
    build:
      context: ./webserver2

  varnish:
    depends_on:
      - nginx    
    build:
      context: ./cache  
    ports: 
      - "8080:80"

  loadbalancer:
      build:
        context: ./loadbalancer
      ports:
        - "8000:8000"
