version: "3"
services:    
  mysql:
    environment: 
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    build:
      dockerfile: Dockerfile
      context: ./database
    ports: 
      - "3306:3306"

  webserver:
    build:
      dockerfile: Dockerfile
      context: ./web

      
