version: "3"
services:
  nginx: 
    build: 
      context: ./webserver
    ports: 
      - 8088:8088
    restart: always

  varnish:
    depends_on:
      - nginx    
    build:
      context: ./cache
    ports:
      - 81:81
